version: "3.7"

services:
  app:
    build: .
    container_name: lauch-frontend-app
    restart: unless-stopped
    entrypoint: dockerize -template ./.env.example:.env ./.docker/entrypoint.sh
    volumes:
      - .:/var/www
    networks:
      - lauch-frontend-network

  nginx:
    build: ./.docker/nginx
    container_name: lauch-frontend-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8200:80"
    volumes:
      - .:/var/www
    networks:
      - lauch-frontend-network
    depends_on:
      - app

networks:
  lauch-frontend-network:
    driver: bridge
